### ISSUE TITLE
Is that working ?

### ISSUE THREAD

**Issue by songhanpoo** [gerwout/pacs#10]
I have followed your instruction. but failed. 
is that working?

`(pacs-venv) root@node1:/opt/venvs# /opt/venvs/pacs-venv/bin/gunicorn app -b 0.0.0.0:5000
[2021-08-03 15:35:25 +0000] [12544] [INFO] Starting gunicorn 20.1.0
[2021-08-03 15:35:25 +0000] [12544] [INFO] Listening at: http://0.0.0.0:5000 (12544)
[2021-08-03 15:35:25 +0000] [12544] [INFO] Using worker: sync
[2021-08-03 15:35:25 +0000] [12547] [INFO] Booting worker with pid: 12547
[2021-08-03 15:35:25 +0000] [12547] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venvs/pacs-venv/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2021-08-03 15:35:25 +0000] [12547] [INFO] Worker exiting (pid: 12547)
[2021-08-03 15:35:25 +0000] [12544] [INFO] Shutting down: Master
[2021-08-03 15:35:25 +0000] [12544] [INFO] Reason: Worker failed to boot.
(pacs-venv) root@node1:/opt/venvs# /opt/venvs/pacs-venv/bin/gunicorn -b 0.0.0.0:5000`

**Comment by gerwout** [comment]
Hi @songhanpoo,

This is most likely caused, because you are trying to run the application from within the virtual environment.
You need to run this from within the folder that contains app.py. The first argument app basically tells gunicorn what Python script to execute and it currently is not able to find it.
